package atm;

public enum TaskName {
	BALANCE_ENQUIRY, WITHDRAW_CASH, DEPOSIT_CASH, DEPOSIT_CHEQUE, TRANSFER_FUND, GENERATE_DEPOSIT_REPORT,
	GENERATE_WITHDRAWAL_REPORT, PRINT_TRANSACTIONS_REPORT, ATM_CASH_ENQUIRY, TURN_ATM_OFF, TURN_ATM_ON, REFILL_ATM_INK
}
